### ISSUE TITLE
GPL license still mentioned on front page

### ISSUE THREAD

**Issue by arokem** [reanahub/reana#105]
The front page (http://www.reana.io/) still mentions the GPL license, but IIUC the project is no longer under GPL since #86 was merged. I apologize if this is already recorded elsewhere.

**Comment by tiborsimko** [comment]
@arokem Thanks, the project web site template text was changed to display MIT already https://github.com/reanahub/reana.io/pull/31 but the new version has not been deployed yet, because the last officially released REANA v0.3.x packages on PyPI and RTD are licensed under GPL. We plan to release REANA v0.4.0 packages on PyPI with the new MIT license soon and we'd update the project web site then. Should happen within a week or so, since we don't plan to add much new functionality, rather mainly to "officialise" the license change (via official releases) everywhere in this way...

**Comment by arokem** [comment]
That makes sense. Sorry for the noise! And thanks for the great project!
