### ISSUE TITLE
validate: warn about using non-tagged latest images

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#248]
If a given user uses a certain image `username/myanalysisimage` always pointing to `latest` we will face the following problem:
- The user will run the workflow once and REANA will pull `username/myanalysisimage:latest` with the hash `4ac0e1872789`
- The user realizes that there is something wrong in the image resulting in an error
- The user fixes it and builds a new image `username/myanalysisimage:latest` which is in reality a new image with hash `879952dab949`
- REANA, when it creates a Kubernetes job, [does not set an image pull policy](https://github.com/reanahub/reana-job-controller/blob/9e0c1fa930eedc13bc9bd0492eee58f12d439f99/reana_job_controller/kubernetes_job_manager.py#L87-L120) so it [falls back to the default `IfNotPresent`](https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  - This means that, if the user job is allocated in a node where `username/myanalysisimage:latest` with hash `4ac0e1872789` is present, the new  `879952dab949` won't be pulled
- The user will expect to have the new image (`879952dab949`) which was just pushed to the Docker registry but in reality, the analysis will be run with `4ac0e1872789` resulting in the same old error

Possible solutions:
- Set all Kubernetes to `imagePullPolicy: Always`, leading into a performance issue, all jobs will be delayed because a image pull needs to be performance, and what is more, the network would be overloaded
- User contacts us, admin makes an intervention: `for node in $(kubectl get nodes); do ssh -i reana.pem fedora@$node 'sudo su - root docker rmi username/myanalysisimage'`
- Allow users to specify `-o image-force-pull` as a workflow operational option when they face this problem

**Comment by tiborsimko** [comment]
Fully-working admin-level one-line solution:

```console
$ for node in $(kubectl get nodes | grep reana | awk '{print $1;}'); do ssh -q -i ~/.ssh/reana.pem -o StrictHostKeyChecking=no fedora@$node 'sudo docker rmi reanahub/reana-env-root6:latest'; done
```

It takes about ~14 seconds to delete an image from all nodes, and about ~40 seconds to repull already-existing images.

Hence we are ready with the solution number two.

Still, the solution number three would be nice to have one day as well, since it would allow end users to directly influence the image pulling policy by themselves. Let's see whether we shall have time later. 

(Moving to the Final kanban board.)

**Comment by tiborsimko** [comment]
Another timing data item: pulling of `reanahub/reana-env-jupyter` serially to all nodes takes ~3 minutes.

**Comment by diegodelemos** [comment]
Moving this to [Awesome-Workshop-Morrows](https://github.com/orgs/reanahub/projects/30) as we know this is fixable with https://github.com/reanahub/reana/issues/248#issuecomment-576631087 for the time being.

**Comment by tiborsimko** [comment]
What we can do to warn the user:
- enrich docs.reana.io to say that using `latest` tag is bad, see e.g. https://vsupalov.com/docker-latest-tag/
- enrich `reana-client validate` that would not only try to validate the workflow, but also discover if images have a tag or not, and warn the user proactively if they do.  (A part of the "better linting" work package, as it were.)

**Comment by tiborsimko** [comment]
(1) We need to create a new click option `validate --environments` where all this work (and some other tickets) will be plugged under.

(2) This issue is about creating `check_environment_tags()` function that will go through all runtime environment specified by the researcher and check whether it uses "latest" tag, or no tag, in which case it should return a warning.

(3) Note that the implementation will differ based on which workflow engine people use:

- Serial
- Yadage
- CWL

Take RooFit demo as an example.

For Serial, the environment is specified under "environment" label in "reana.yaml". The code should read the strings from there, and check if there is ":sometag", and if sometag is not latest.

For Yadage, the tag is specified in `imagetag` in workflow specs, which are read by the client after "reana.yaml" is read.

For CWL, the tag is specified under 'dockerPull` in workflow specification.

See `rg 6.18.04` for location of all the places.

Implementation-wise, the `check_environment_tags()` function should support all the three engines. There could be three atomic functions implementing the check for each engine.

(4) We could later create test cases, since this is basically a string manipulation task, it should be relatively straightforward.

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/pull/468
