### ISSUE TITLE
docs: from readthedocs.io to docs.reana.io

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#335]
Move documentation out of readthedocs.io into docs.reana.io.

Keep only what is necessary on readthedocs.io especially if it is auto-generated, e.g. click docs.

Keep redirections from readthedocs.io to the new canonical docs.reana.io documentation site.

(Consider perhaps even redirecting whole domain e.g. reana-job-controller.rtfd.io into docs.reana.io and not keeping any on rtfd.io.)

**Comment by tiborsimko** [comment]
@mvidalgarcia @diegodelemos Was everything moved already and the remaining issues for more verbose text ticketised? Can we close this epic issue already?

**Comment by mvidalgarcia** [comment]
> @mvidalgarcia @diegodelemos Was everything moved already and the remaining issues for more verbose text ticketised? Can we close this epic issue already?

https://github.com/reanahub/reana-cluster/pull/268 is slightly related but can be a separate matter. I think the rest is moved.

**Comment by diegodelemos** [comment]
We are just missing a few repositories because of build problems:
- RWC doesn't get triggered in RTFD since ~1 year (see [here](https://readthedocs.org/projects/reana-workflow-controller/builds/))
- RJC fails in its latest build, error [here](https://readthedocs.org/projects/reana-job-controller/builds/11601995/)
- REANA fails in its latest build, error [here](https://readthedocs.org/projects/reana/builds/11616759/)

**Comment by tiborsimko** [comment]
`reana` and `r-w-controller` are now OK; the only remaining repository is `r-j-controller`. Created an issue there.
