### ISSUE TITLE
cli: shared modules are not upgraded correctly

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#412]
Running `reana-dev git-upgrade-shared-modules -c r-server` requirements (in setup.py) were upgraded to the following:

```diff
- "reana-db>=0.7.0a6,<0.8.0",
+ "reana-db>=0.8.0a1,<0.8.0",
```

while the correct output would be:
`"reana-db>=0.8.0a1,<0.9.0",`

**Comment by tiborsimko** [comment]
This is connected to the fact that `master` is now being used for both 0.7.0 work and 0.8.0 work.  

We need to start `maint-0.7` branches rapidly so that we can cleanly separate these works. Then we'll be able to amend setup requirements everywhere.

Note also #413 that is related and that will come very handy for these situations.

**Comment by tiborsimko** [comment]
`maint-0.7` created everywhere in CLIENT and CLUSTER repositories, and there are many PRs to update `master` lower pins, so this will be fixed soon.

**Comment by tiborsimko** [comment]
OK, installation problem fixed... Remains to amend `git-upgrade-shared-modules` command to properly upgrade top boundary, which was the core of the issue :wink:
