### ISSUE TITLE
global: start using flake8 linter

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#456]
> An example of Python code problems that flake8 can catch is there: reanahub/reana-commons#235
Personally I have flake8 plugged into my editors, so I see these locally. However, one has to have a special configuration defined so that flake8 plays nicely with black. I'm using the following:

> 
```
$ cat ~/.config/flake8
[flake8]
ignore = E203, E231, E266, E501, W503, F403, F401
max-line-length = 89
max-complexity = 18
select = B,C,E,F,W,T4,B9
```

see https://github.com/tiborsimko/dotfiles/blob/master/flake8/.config/flake8

> So if we want to use flake8 for REANA, the first thing would be to agree on some sane black-friendly defaults and use them in our editors

Some of the repos were covered with `flake8` in this [PR](https://github.com/reanahub/reana/issues/450)

- [x] [pytest-reana](https://github.com/reanahub/pytest-reana/pull/76)
- [x] [reana](https://github.com/reanahub/reana/pull/457)
- [x] [reana-client](https://github.com/reanahub/reana-client/pull/448)
- [x] [reana-commons](https://github.com/reanahub/reana-commons/pull/239)
- [x] [reana-db](https://github.com/reanahub/reana-db/pull/115)
- [ ] reana-demo-atlas-recast
- [ ] reana-demo-bsm-search
- [ ] reana-demo-cms-h4l

**Comment by tiborsimko** [comment]
The `reana-demo-*` are usually physics-oriented examples, most contain user-contributed code that we won't be linting.  The most important repositeries are REANA components and those examples that we have created some factory code for.

This leaves us with only the following three repositories:

```console
$ for repo in $(ls -1); do cd $repo; echo "==> $repo"; flake8; cd ..; done
==> reana-cluster
./docs/conf.py:12:1: F401 'os' imported but unused
./docs/conf.py:14:1: F401 'sphinx.environment' imported but unused
==> reana-demo-cms-reco
./setup.py:50:21: W605 invalid escape sequence '\s'
./setup.py:50:25: W605 invalid escape sequence '\s'
./cms_reco/cli.py:13:1: F401 'os' imported but unused
./cms_reco/cli.py:84:80: E501 line too long (80 > 79 characters)
./cms_reco/utils.py:213:5: F841 local variable '_cod_client' is assigned to but never used
./cms_reco/utils.py:214:5: F841 local variable '_get_config_cmd' is assigned to but never used
./docs/conf.py:28:1: F401 'sphinx.environment' imported but unused
./docs/conf.py:205:2: W292 no newline at end of file
./tests/utils_test.py:57:23: F541 f-string is missing placeholders
==> reana-ui
./docs/conf.py:15:1: F401 'sphinx.environment' imported but unused
./docs/conf.py:165:80: E501 line too long (80 > 79 characters)
```

The `reana-cluster` is deprecated, and `reana-ui` is not primarily a Python shop, so these are not really needed to convert.

Hence `reana-demo-cms-reco` might be the only one to address additionally, but since that code is also a kind of demo, it can wait.

For the purposes of this issue, all the most important repositories (`-c CLIENT -c CLUSTER`) are all done and verified having flake8 enabled in the CI:

```console
$ rg lint-flake8 */.github/workflows/ci.yml | wc -l
13
```

I'm therefore closing the issue.
