### ISSUE TITLE
Make Web UI Sign-up Optional

### ISSUE THREAD

**Issue by hollowec** [reanahub/reana#469]
Hi,

Would it be possible to make the Web-UI signup functionality optional?  Perhaps a value that can be overidden during the helm installation?

**Comment by tiborsimko** [comment]
BTW while we are at this, perhaps we can style the sign-up page a bit differently, because currently the two pages (sign-up and sign-in) are styled IIRC exactly the same, so users may not even notice where they are.

We can leave only one big sign-in button with a small text underneath "If you do not have an account yet, please _sign up here_" (and the link will bring people to a dedicated sign-up page, where we could later have captcha and email verification and stuff).

And, for this ticket at hand, the text under sign-in would simply read "If you don't have an account yet, please contact _REANA administrators_" with a mailto for site admins.

So the sign-in UI design would be similar for the two cases.

**Comment by mvidalgarcia** [comment]
Discussed offline: 

> Keep the sign-up form always and enable Invenio-Accounts email confirmation so the account is only usable once confirmed. After that, the user must request the token as usual.

@hollowec would this fulfill your needs?

**Comment by hollowec** [comment]
Hi @mvidalgarcia , that would help a lot, but I would prefer to also have the option to disable the sign-up completely if possible.

**Comment by mvidalgarcia** [comment]
> Hi @mvidalgarcia , that would help a lot, but I would prefer to also have the option to disable the sign-up completely if possible.

The problem with this approach is that, 
- a) At the moment, [as you well mentioned on Gitter](https://gitter.im/reanahub/reana?at=5fbe760d771c185e0ec788cb), it's not possible to set a password to newly created users via `reana-admin`;
- b) If we implement this, the safest way to do it would be autogenerating a random password for the new user. Then, it'd responsibility of the admin to send this password to the user, with the safety problems that it involves;
- c) We still don't have the possibility for users to change their password, so that autogenerated password would be _compromised_ from the very first moment. We will have to make the changing password available before.

If enabling email confirmation would already help a lot, we will most likely implement this first, as it seems the easiest/fastest/most common approach to us, and then we will consider applying the rest of the functionalities. I'm pretty sure that some of them such as changing passwords will come sooner or later.

Thanks so much for your input!

**Comment by hollowec** [comment]
Hi @mvidalgarcia, OK sounds good, thanks!  Can captcha be enabled for sign-up as well?

**Comment by mvidalgarcia** [comment]
> Hi @mvidalgarcia, OK sounds good, thanks! Can captcha be enabled for sign-up as well?

We will definitely explore this option in the future.

**Comment by mvidalgarcia** [comment]
Closing this as the main functionality has been implemented and published in the [0.7.2 release](https://blog.reana.io/posts/2021/reana-0.7.2/).

Separate issue created for the captcha implementation: https://github.com/reanahub/reana-ui/issues/177
