### ISSUE TITLE
helm: set default memory limit value for user job containers

### ISSUE THREAD

**Issue by audrium** [reanahub/reana#509]
`REANA_KUBERNETES_JOBS_MEMORY_LIMIT` is being used in `reana-job-controller` to set the limit of the jobs that are submitted. Currently it does not have any default value. To calculate the [workflow complexity](https://github.com/reanahub/reana-server/pull/366) some default value was needed. Ideally, the default values should be set in Helm values.

More context can be found in the discussion:
_Originally posted by @tiborsimko in https://github.com/reanahub/reana-server/pull/366#discussion_r645516762_

**Comment by audrium** [comment]
We might expose `REANA_SCHEDULER_SECONDS_TO_WAIT_FOR_REANA_READY` via Helm values in the same go.

_Originally posted by @tiborsimko in https://github.com/reanahub/reana-server/pull/370#discussion_r649745377_

**Comment by mvidalgarcia** [comment]
`REANA_KUBERNETES_JOBS_MEMORY_LIMIT` can be already set via Helm values through `.Values.kubernetes_jobs_memory_limit`. However, we [currently require to have a `.Values.node_label_runtime` set](https://github.com/reanahub/reana/blob/2c5df09dc9f6fa02e0321330ec79af9bbe480a0d/helm/reana/templates/reana-workflow-controller.yaml#L95) to be able to set `.Values.kubernetes_jobs_memory_limit`. How should we deal with this in order to set a default memory limit? Theoretically, we can stop requiring `node_label_runtime` even though it seems like a good practice.

**Comment by tiborsimko** [comment]
I think it may be good to require the job runtime label in all cases. One merit is that it'll incite cluster admins to think about node separation and safety. (And, for single-node clusters, we could actually tag the node with all the necessary labels to make it work.  So the only downside would be to having to launch some extra commands during installation.)

Thinking of defaults, it may be perhaps good to also set a default memory limit to some example value, such as 8 GiB, by default. Again with the merit of inciting admins to adapt it on their deployments, based on the node RAM sizes. It may be better than leaving it undefined and seeing scheduling troubles later with nodes dying out. 

(We could also think about indicating memory limit visibly to the users, in reana-client CLI or also on the Web UI, so that they wouldn't be surprised to see their long-running jobs being killed after five days or so due to OOM.)

Just musing out loud... We could ponder IRL.
