### ISSUE TITLE
reana-dev git-create-release-commit -c reana should increment also version

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana#516]
Currently `reana-dev git-create-release-commit -c reana` creates a release branch and increments Helm version in `helm/reana/Chart.yaml`.

It should also update `reana/version.py`.

Note: this is an interesting use case of git tags following semver2 while the compontent is a Python package so should _also_ follow PEP 0440 for `version.py`.

**Comment by VMois** [comment]
After looking into the code, I discovered a few issues that need to be discussed:

(1) if `next_version` is specified as `semver2`, Python bump will not work as it is in pep0440 format. 

*suggestion*: we have a `pep0440 to semver2` convertor. We could minimize the amount of engineering by forcing `next_version` to be in pep0440 format. Otherwise, I will need to develop a `semver2 to pep0440` converter.

(2) `get_current_component_version_from_source_files` function return the first version it will find out of helm, python or JS files. This creates two issues:

(2.1) if the helm file exists, it will return the helm file version and skip everything after. So, for example, if a python file exists and its version is different from the helm file, it will still return the helm version. If we are planning to have different versions of `helm` and `python` in the SAME component this is an issue.

(2.2) the function can return semver2 or pep0440 version (depending on the helm or python file), which is not consistent. If we want to bump both Python and Helm we need to get both versions formats. So, `get_current_component_version_from_source_files` needs to return list or dict instead of string. This is not hard to change, but the function is used in multiple places and it makes things more complicated.

What are your thoughts? Basically, I need a more detailed description of how the bumping process should behave. Thank you.

**Comment by audrium** [comment]
My 2 cents. I think the easiest way to solve this would be:
1) `get_current_component_version_from_source_files()` could have a flag to start searching for a version either from helm or from python version files (some functions like `release_helm()` will still need the `helm` version)
2) currently `bump_component_version()` finds the right version files to update with `get_component_version_files()`, but only updates the `helm` one if it's present. So if we could have `pep440` version there as a `current_version`, we could easily update python version and helm version (by using the `pep0440` to `semver2` converter) in one go. 
3) downsize of this approach is that we would break git tags for `reana` component (it would complain that current_version is not tagged), since it's currently in `semver2 while all the others are in `pep0440`.

**Comment by VMois** [comment]
Created a PR. One question I have, what if Python and Helm versions must be different (or Python and OpenAPI)? Was it a case at least once? If yes, we will need to add a flag to indicate what version file we want to bump.
