### ISSUE TITLE
benchmark: similar to workflow range, add time range to analyze command

### ISSUE THREAD

**Issue by VMois** [reanahub/reana#583]
Currently, there is workflow range option `-n` that allows selecting workflows numbers that will be plotted in the execution progress plot. In some cases, it is beneficial to limit the plot by time range to make it more visible.

We already have the`-t` option for `--title` so a new time range option might be named `--time`.

**Comment by tiborsimko** [comment]
Useful especially when some run fail due to ops issues, such as here:

![susy201816-3i-30b-134j-submit500-sleep0-total500-run20211118b_execution_progress_1_500](https://user-images.githubusercontent.com/517546/142632200-6456c535-a321-4382-8719-b92ead0665a6.png)

**Comment by VMois** [comment]
*question:* 1. What should be the value of `--time`? Absolute (like `--time 2021-11-22T12:00:00-2021-11-22T13:00:00`) or relative to some event (first entry)?

I think absolute will be better here. Easier to the plot. One disadvantage is that entering absolute format is a long process + `-` in the middle between start/end time can be confusing.

**Comment by tiborsimko** [comment]
Yes, using absolute time is good. We could do `--datetime-from value1 --datetime-until value2` perhaps, which should solve the problem of "invisible" middle dash in your example above.

**Comment by tiborsimko** [comment]
(But, for consistency with `-n 1-250`, we could simply use `--datetime value1-value2` as well; I guess people will get used to the "invisible" middle dash. It should be OK as well.)

**Comment by VMois** [comment]
*question:* Should `--datetime` range affect other plots (histograms, execution_status) besides execution_progress?

if `--datetime` will have to affect other plots it will most probably require more development time. If it will not affect it brings inconsistency to histograms and execution_status plots.

What do you think?

*suggestion:* I am more inclined towards `--datetime` that affects all plots but don't have a clear picture of how to implement it yet.

**Comment by tiborsimko** [comment]
It's not so easy for datetime1-datetime2 to affect other plots. E.g. take workflow status (running, queued, etc), this is mostly a snapshot in time of where we are; while datetime1-datetime2 is an interval in time. Perhaps the workflow status pie chart could give a snapshot view at the datetime1 precise time, and at the datetime1 precise time, i.e. produce two pie chart plots, corresponding the beginning and the end of the desired timee interval. 

Actually, if the time interval axis would be split into 5 ticks, the workflow status pie chart graph could produce five pie charts, corresponding to the times of the x-axis ticks. That would be pretty cool, as it would give another insight of what's been happening at the time. (Similarly to how many r-b and r-j pods were running at the time; coming later.)

As for runtime histograms, it is also not easy to create them until all workflows are finished. One possibility could be to include only those that either failed or finished by the given x-axis tick time. So the running ones would not be counted, because we don't really know anything yet about their running time. We would treat only failed ones and finished ones regarding runtime, and we would treat all that were started regarding pending time. Anyway, it's not so straightforward to implement, so I'd say we could leave these aside for now... And we can simply indicate that the histogram snapshot is done at the datetime2 i.e. finish time.

**Comment by VMois** [comment]
`datetime1-datetime2` affects what data is selected for the `execution_progress` plot. So if we want to have a consistent picture for all plots, we should also select the same data for the `execution_status` plot and histograms. Data is the same for all plots, they just interpret (plot) it differently.

Currently, if the workflow is not finished, histograms use `collected_date` (the time when the `collect` command was run) to calculate `pending_time` and `runtime`.

**Comment by tiborsimko** [comment]
> Currently, if the workflow is not finished, histograms use collected_date (the time when the collect command was run) to calculate pending_time and runtime.

We cannot do that, since we could collect a workflow that just started ten seconds ago... That would skew the runtime histogram statistics. Basically, if we don't know the exact runtime, we should not include the given run in the histograms. Such a still-running workflow would be only represented in the pie chart, in the category "running", but wouldn't be represented in the runtime histogram, where only those that are "finished" should go. (And perhaps "failed", but that could be rather another histogram of those that failed... Since if a run fails early, it would perturb the "real runtime" numbers similarly).

**Comment by tiborsimko** [comment]
> datetime1-datetime2 affects what data is selected for the execution_progress plot. So if we want to have a consistent picture for all plots, we should also select the same data for the execution_status plot and histograms

Sure! But my point above was that the progress plot is time interval, whilst status plot is a snapshot point in time (taken at the end of the run).  So if users specify datetime1 and datetime2, we have to pick one to represent status snapshot. Could be at datetime2, but even better could be five plots at ticks from datetime1 to datetime2.

**Comment by VMois** [comment]
> > Currently, if the workflow is not finished, histograms use collected_date (the time when the collect command was run) to calculate pending_time and runtime.
> 
> We cannot do that, since we could collect a workflow that just started ten seconds ago... That would skew the runtime histogram statistics. Basically, if we don't know the exact runtime, we should not include the given run in the histograms. Such a still-running workflow would be only represented in the pie chart, in the category "running", but wouldn't be represented in the runtime histogram, where only those that are "finished" should go. (And perhaps "failed", but that could be rather another histogram of those that failed... Since if a run fails early, it would perturb the "real runtime" numbers similarly).

It looks like a new issue for the benchmark script is needed. I will create one to only use `finished` workflows for histograms.

**Comment by VMois** [comment]
> > datetime1-datetime2 affects what data is selected for the execution_progress plot. So if we want to have a consistent picture for all plots, we should also select the same data for the execution_status plot and histograms
> 
> Sure! But my point above was that the progress plot is time interval, whilst status plot is a snapshot point in time (taken at the end of the run). So if users specify datetime1 and datetime2, we have to pick one to represent status snapshot. Could be at datetime2, but even better could be five plots at ticks from datetime1 to datetime2.

Got it. There is another issue I am thinking about - how to define a "snapshot". We have columns like `created`, `asked_to_start_date`, `started`, and `ended` that all contain datetimes. What column(s) to use for a snapshot?

Imagine the situation where a single workflow *partially* exists in a time range (created and started inside the time range but finished after). Options:

- we could include workflow into the range but then the workflow status pie plot will be inaccurate because the status is *"finished"*, so we will need to update the workflow status to either "running" or "pending";

- we will not include this partial workflow, which will not represent the real picture (workflow at this time was either "running" or "pending").

One observation is that statement "`created` < `asked_to_start_date` < `started` < `ended`" is always be true for each workflow.

*OR*, just as a reminder, we have another approach:

We can just forget about pie and histograms (they will work as before), and just use the time range on the `execution_progress` plot only to zoom. Basically, we will treat the time range as we treat the `title` option - cosmetics for the plot.

What do you think? Should we push for time range and snapshots, or only focus on the `execution_progress` plot?

**Comment by VMois** [comment]
There is [draft PR](https://github.com/reanahub/reana/pull/596) to show how changes will look like if we can forget about the status pie chart and histograms and treat `time range` as plot parameter for execution_progress plot.
