### ISSUE TITLE
Unable to deploy cluster locally

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#647]
Hello,
I was following the steps described here: https://docs.reana.io/administration/deployment/deploying-locally/
In the helm install I am getting an error on versions mismatch
```
helm install reana reanahub/reana --namespace reana --create-namespace --wait
Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.13.0-0 < 1.22.0-0 which is incompatible with Kubernetes v1.24.0
```
I try to downgrade the kubectl but it is still bringing the server version above it
```
/usr/local/bin/kubectl version --short 
Client Version: v1.22.11
Server Version: v1.24.0
WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1
```
I appreciate any workaround.

Thank you beforehand.

**Comment by tiborsimko** [comment]
Hi @arm2arm:

Kubernetes v1.24 clusters are supported only in REANA's bleeding-edge `master` branch sources. It works well, but we have not released the new Helm chart yet. Hence it does not work out of the box yet.

Are you just trying out REANA locally using Kind or are you thinking about deploying on a "proper" Kubernetes v1.24 cluster later?

If mostly the former, the easiest solution to test locally would be to force Kind to use an older Kubernetes cluster version. Assuming you are using the latest stable Kind v0.14 release:

```
$ kind version
kind v0.14.0 go1.18.2 linux/amd64
```

you can use the following `--image` option value to bring up Kubernetes v1.21 instead of the default v1.24:

```
$ kind delete cluster
$ kind create cluster --config kind-localhost-30443.yaml --image=kindest/node:v1.21.12
```

This is the only change necessary to install REANA 0.8.1 stable release locally on your Kind v0.14.

Can you please give it a try?

P.S. Another useful trick, if you are interested in testing out our REANA 0.9.0-alpha.* developer preview versions from our [release list](https://reanahub.github.io/reana/), would be the following: 

```
$ helm install ... --version 0.9.0-alpha.5
```

This would bring up REANA 0.9.0 latest alpha release instead of the above 0.8.1 latest production release.

(And, once we release `0.9.0-alpha.6` officially, Kind v0.14 will be supported out of the box, so the above `kind create ... --image` option would not be necessary anymore.)

**Comment by arm2arm** [comment]
Hi @tiborsimko,
Thank you for the excellent answer! The kind option: **--image=kindest/node:v1.21.12** did the trick.
we are trying to run locally in our for some external users from punch4nfdi consortium. first trial of interdisciplinary  service astro vs particles :)
maybe in meanwhile you could add it in the documentation on the main page, because kubernetes-release v1.24.2  is marked as a stable
