### ISSUE TITLE
helm: let administrators disable the default retention period

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana#653]
[...]
2. I think it should be possible to disable the maximum retention period, as we do for the disk/cpu quota limit. WDYT?
[...]

_Originally posted by @mdonadoni in https://github.com/reanahub/reana/issues/652#issuecomment-1172474025_

In case we decide to provide a way to disable the default retention period, we would also need to modify how we handle the `WORKSPACE_RETENTION_PERIOD` env variable in reana-server.

**Comment by VMois** [comment]
Default disk/cpu limits are `None` which means they are infinite. Maybe, for the workspace retention period, the default value should be None ("store forever"). If we need to specify the maximum allowed retention period by the users we need to introduce a different env variable. The same way we are doing with Kubernetes memory or timeout limits.

**Comment by VMois** [comment]
If we want to define some value that will mean "infinite" or "forever" workspace retention, we cannot use `0`. In some future, `0` can mean "delete files immediately after the workflow is finished". 

As of now, what about using such values:

`1-*` - the same way we have it right now,  `WORKSPACE_RETENTION_PERIOD` will equal some integer > 0;
`forever` - keep files forever, `WORKSPACE_RETENTION_PERIOD` will equal `-1`;

*note:* for the "forever" value, I would prefer using `None` as it better conveys a message for developers, in my opinion. It means "no retention period, keep forever" or "retention_days is None, so keep forever". The issue is that our current DB model for the `retention_days` field is not nullable ([code](https://github.com/reanahub/reana-db/blob/a1bb1e5cbd7ff314f27f2e7bde2defc79cdd0196/reana_db/models.py#L912)).

So it will look like this for admins:

```yaml
workspace_retention_period: forever
# or
workspace_retention_period: 30
```
