### ISSUE TITLE
How to enable quotas per user?

### ISSUE THREAD

**Issue by arm2arm** [reanahub/reana#661]
Dear developers,
We have deployed in our enviroment a test instance for Punch4NFDI project. Works as expected, but one question is remaining how to setup quotas for the individual users? I did not find anything in the docs, maybe some one count point us in to the right direction?
Currently client side  shows that:
```
(reana) ~/test-plot$ reana-client quota-show --resources
cpu
disk
(reana) ~/test-plot$ reana-client quota-show --resource disk --report limit -h
No limit.
(reana) ~/test-plot$ reana-client quota-show --resource cpu  --report limit -h
No limit.
```

Thank you beforehand.

**Comment by VMois** [comment]
Hi! Thank you for raising the issue. You are right on time because we have been working on improving our docs for quotas. As of now, the PR is [in review](https://github.com/reanahub/docs.reana.io/pull/139), but you can still check instructions [here](https://github.com/VMois/docs.reana.io/blob/admin-user-quotas/docs/administration/configuration/configuring-user-quotas/index.md).

If you have any questions, don't hesitate to ask. It is a nice opportunity to make quota documentation better.

**Comment by arm2arm** [comment]
working!
