### ISSUE TITLE
docker: build and publish ARM images

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana#753]
We should investigate whether it's possible to run REANA on ARM, fix the issues which might arise and then start publishing multi-platform images to DockerHub. This is makes it possible to deploy REANA locally (i.e. researcher oriented method) on M1/M2 Macs, for example.

**Comment by tiborsimko** [comment]
I'll make a set of PRs amending REANA compoments to build on Apple M2 silicon using the following packages:

```console
$ helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.21.3"}

$ kind version
kind v0.20.0 go1.20.5 darwin/arm64

$ podman version
Client:       Podman Engine
Version:      4.7.1
API Version:  4.7.1
Go Version:   go1.21.3
Git Commit:   ef83eeb9c7482826672f3efa12db3d61c88df6c4
Built:        Thu Oct  5 15:21:06 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.7.0
API Version:  4.7.0
Go Version:   go1.20.8
Built:        Wed Sep 27 20:24:25 2023
OS/Arch:      linux/arm64
```

This note will be used to track the progress:

- [ ] reana-auth-vomsproxy (needs upgrade from CC7 to e.g. EL9 to have `arm64` architecture)
- [ ] reana-job-controller
- [ ] reana-ui
- [ ] reana-workflow-engine-cwl
- [ ] reana-workflow-engine-serial
- [ ] reana-workflow-engine-snakemake
- [ ] reana-workflow-engine-yadage (needs `config.guess` updates for the installation of `jq`)

Otherwise REANA is working fine on Apple M2 and executes well CWL, Serial, Snakemake demo workflows. 

Noticed that whilst the opening of notebooks work, I cannot open terminal: something to look into.
